### ISSUE TITLE
Document each individual accent colour

### ISSUE THREAD

**Issue by thomasjbradley** [thomasjbradley/jekyll_patternbot#10]
Should there be a way to document each individual accent colour? Maybe more CSS comments?

```css
:root {
  /* @doc This accent colour is great for bright things */
  --color-yellow-bright: #ff0;
}
```

Maybe for typefaces too?

```css
:root {
  /* @doc Font is amazing! */
  --font-awesome: Georgia, serif
}
```
